ProjeCore/Models/Admin.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjeCore.Models
{
    public class Admin
    {
        [Key]
        public int AdminID { get; set; }

        [Column(TypeName = "Varchar(20)")]
        public string Kullanici { get; set; }


        [Column(TypeName = "Varchar(10)")]
        public string Sifre { get; set; }


    }
}

ProjeCore/Models/Birim.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjeCore.Models
{
    public class Birim
    {
        [Key]
        public int BirimID { get; set; }
        public string BirimAd { get; set; }
        public IList<Personel> Personels { get; set; } // interface list formatında, ilişkiyi bu alanda alacağız.
    }
}

ProjeCore/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace ProjeCore.Models
{
    public class Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=(localdb)\\MSSQLLocalDB; database=BirimDB; integrated security=true");
        }

        public DbSet<Birim> Birims { get; set; }
        public DbSet<Personel> Personels { get; set; }
        public DbSet<Admin> Admins { get; set; }

    }
}

ProjeCore/Models/ErrorViewModel.cs
using System;

namespace ProjeCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjeCore/Models/Personel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;


namespace ProjeCore.Models
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }

        public int BirimID { get; set; }
        public Birim Birim { get; set; } // Bire çok ilişki için Birim sınfından bir nesne türettim.
    }
}

ProjeCore/Controllers/BirimController.cs
using Microsoft.AspNetCore.Mvc;
using ProjeCore.Models;
using System.Linq;

namespace ProjeCore.Controllers
{
    public class BirimController : Controller
    {
        Context context = new Context();
        public IActionResult Index()
        {
            var degerler = context.Birims.ToList();
            return View(degerler);
        }


        [HttpGet] // Sayfa yüklendiği zaman burası çalışcak.
        public IActionResult YeniBirim()
        {
            return View();
        }

        [HttpPost] // Sayfamda bir post işlemi olursa burası çalışacak
        public IActionResult YeniBirim(Birim birim)
        {
            //Departman Ekleme İşlemi

            context.Birims.Add(birim);

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        // **************************************************************************************

        public IActionResult BirimSil(int id)
        {
            var birim = context.Birims.Find(id);
            context.Birims.Remove(birim);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult BirimGetir(int id)
        {
            // Departman Update işlemi için sayfaya id taşıma...

            var birim = context.Birims.Find(id);
            return View("BirimGetir", birim);
        }

        public IActionResult BirimGuncelle(Birim birim)
        {
            var birimdeger = context.Birims.Find(birim.BirimID);
            birimdeger.BirimAd = birim.BirimAd;
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult BirimDetay(int id) // Detaylara tıkladığımda, o birime ait personeller listelenecek.
        {
            // Personel içerisinde BirimID eşittir, dışarıdan gönderien id ye eşit olan değerleri liste halinde getir
            var degerler = context.Personels.Where(x => x.BirimID == id).ToList();

            var birimValue = context.Birims.Where(x => x.BirimID == id).Select(y => y.BirimAd).FirstOrDefault();
            // FirstOrDefault bana birtane veri getir..

            ViewBag.birimVal = birimValue;
            return View(degerler);
        }


    }
}

ProjeCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjeCore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjeCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjeCore/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using ProjeCore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ProjeCore.Controllers
{
    public class LoginController : Controller
    {
        Context context = new Context();

        [HttpGet]
        public IActionResult GirisYap()
        {
            return View();
        }

        public async Task<IActionResult> GirisYap(Admin admin)
        {
            // Identity kullanacağımız için devreye async ifadeler girer.

            var bilgiler = context.Admins.FirstOrDefault(x => x.Kullanici == admin.Kullanici && x.Sifre == admin.Sifre);

            if (bilgiler != null) {

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name , admin.Kullanici)
                };

                var userIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                await HttpContext.SignInAsync(principal); 
                return RedirectToAction("Index", "Personels");




                /* Notes!
                 * bilgilerden null gelmezse burası çalışır aksi durumda View'i return eder.
                 * İnputlara girmiş olduğum kullanici degeriyle sifre değeri eşleşirse null dönmeyecek.
                 * claims: talepler
                 * ClaimsPricipal: Birden çok talep tabanlı kimliği destekleyen app.
                 * async bir ifadeyi kullanabilmek için önüne 'await' koymak gerekli.
                 */
            }
            return View();

        }
    }
}

ProjeCore/Controllers/PersonelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjeCore.Models;

namespace ProjeCore.Controllers
{
    public class PersonelsController : Controller
    {
        Context context = new Context();

        [Authorize]
        public IActionResult Index()
        {
            var degerler = context.Personels.Include(x => x.Birim).ToList();

            return View(degerler);
        }


        [HttpGet]
        public IActionResult YeniPersonel()
        {
            List<SelectListItem> degerler = (from item in context.Birims.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = item.BirimAd,
                                                  Value = item.BirimID.ToString()
                                              }).ToList();
            ViewBag.values = degerler;
            return View();
        }

        [HttpPost]
        public IActionResult YeniPersonel(Personel personel)
        {
            var personels = context.Birims.Where(x => x.BirimID == personel.Birim.BirimID).FirstOrDefault();
            personel.Birim = personels;
            context.Personels.Add(personel);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjeCore/Views/Birim/BirimDetay.cshtml
@using ProjeCore.Models
@model List<Personel>

@{
    ViewData["Title"] = "BirimDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<div>
    <h2>@ViewBag.birimVal</h2>
</div>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelID</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Sehir</td>
        </tr>
    }
</table>

ProjeCore/Views/Birim/BirimGetir.cshtml
@model ProjeCore.Models.Birim
@{
    ViewData["Title"] = "BirimGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}


@using (Html.BeginForm("BirimGuncelle", "Birim", FormMethod.Post))
{
    <b>Birim İD</b>
    @Html.TextBoxFor(x => x.BirimID, new {@class = "form-control"})

    <br />

    <b>Birim Adı</b>
    @Html.TextBoxFor(x => x.BirimAd, new {@class = "form-control"})

    <br />
    <button class="btn btn-outline-success">Birim Güncelle</button>
}

ProjeCore/Views/Birim/Index.cshtml
@using ProjeCore.Models
@model List<Birim>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BirimID</td>
            <td>@item.BirimAd</td>
            <td><a href="/Birim/BirimSil/@item.BirimID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Birim/BirimGetir/@item.BirimID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Birim/BirimDetay/@item.BirimID" class="btn btn-info">Detaylar</a></td>
        </tr>
    }
</table>

<a href="/Birim/YeniBirim/" class="btn btn-primary">Yeni Birim</a>

ProjeCore/Views/Birim/YeniBirim.cshtml
@model ProjeCore.Models.Birim

@{
    ViewData["Title"] = "YeniBirim";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}



@{
    ViewData["Title"] = "YeniDepartman";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

<form class="form-group" method="post">

    <b>Birim Adı</b>
    @Html.TextBoxFor(x => x.BirimAd, new {@class = "form-control"})

    <br />
    <button class="btn btn-dark">Birim Ekle</button>
</form>

ProjeCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjeCore/Views/Login/GirisYap.cshtml
@{
    Layout = null;
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="~/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/web/css/font-awesome.css" rel="stylesheet"> <!-- Font-Awesome-Icons-CSS -->

<!-- //Custom Theme files -->
<!-- web font --> 
<link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet"> 
<!-- //web font --> 
</head>
<body>
	<!-- main -->
	<div class="main">
		<h1>MVC Core Login Form</h1>
		<div class="main-w3lsrow">
			<!-- login form -->
			<div class="login-form login-form-left"> 
				<div class="agile-row">
					<h2>Giriş Yap</h2> 
					<div class="login-agileits-top"> 	
						<form action="#" method="post"> 
							<p>Kullanıcı Adı</p>
							<input type="text" class="name" name="Kullanici" required=""/>
							<p>Parola</p>
							<input type="password" class="password" name="Sifre" required=""/>  
							<label class="anim">
								<input type="checkbox" class="checkbox">
								<span> Beni Hatırla ?</span> 
							</label>   
							<input type="submit" value="Login"> 
						</form> 	
					</div> 
					<div class="login-agileits-bottom"> 
						<h6><a href="#">Parolamı Unuttum?</a></h6>
					</div> 
					<div class="login-agileits-bottom1"> 
						<h3>(veya)</h3>

					</div> 
					<div class="social_icons agileinfo">
						<ul class="top-links">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								</ul>
					</div>

				</div>  
			</div>  
		</div>	
		<!-- copyright -->
		<div class="copyright">
			<p> © 2022 MVC Core Login Form. Tüm Hakları Saklıdır. | Design by sayitsamikoca</a></p>
		</div>
		<!-- //copyright --> 
	</div>	
	<!-- //main --> 
</body>
</html>

ProjeCore/Views/Personels/Index.cshtml
@using ProjeCore.Models
@model List<Personel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelID</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Sehir</td>
            <td>@item.Birim.BirimAd</td>
            <td><a href="/Personels/PersonelSil/@item.PersonelID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personels/PersonelGetir/@item.PersonelID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Personels/YeniPersonel/" class="btn btn-primary">Yeni Personel</a>

ProjeCore/Views/Personels/YeniPersonel.cshtml
@model ProjeCore.Models.Personel

@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

<form class="form-group" method="post">

    <b>Personel Adı</b>
    @Html.TextBoxFor(x => x.Ad, new {@class = "form-control"})
    <br />
    <b>Personel Soyadı</b>
    @Html.TextBoxFor(x => x.Soyad, new {@class = "form-control"})
    <br />
    <b>Personel Şehiri</b>
    @Html.TextBoxFor(x => x.Sehir, new {@class = "form-control"})
    <br />
    <b>Personel Birim</b>
    @Html.DropDownListFor(x=>x.Birim.BirimID, (List<SelectListItem>)ViewBag.values, new {@class="form-control"})
    <br />
    <button class="btn btn-dark">Personel Ekle</button>
</form>

ProjeCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjeCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjeCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjeCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ProjeCore/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Core Departman Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
</head>

<body>


    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Birim/Index" class="w3-bar-item w3-button">Birimler</a>
        <a href="/Personels/Index" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>


    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>Asp.Net Core Mvc Proje Geliştirme</h1>
        </div>


        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>